<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Shared\Hotel.Shared.Application\Hotel.Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\Hotel.Shared.Infrastructure\Hotel.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
